#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
  set -x
fi

function checkPhpModules {
    php -m > ~/php_modules.tmp
    echo 'Checking PHP modules...'

    if ! cmp -s ~/php_modules.tmp ~/php_modules; then
        echo 'Error. PHP modules are not identical.'
        diff ~/php_modules.tmp ~/php_modules
        exit 1
    fi

    echo 'OK. PHP modules are identical'
}

function checkTools {
    echo 'Checking tools...'
    composer --version | grep -q 'Composer version' && echo 'Composer installed'
    ssh -V &>/dev/null && echo 'SSH Client installed'
}

checkPhpModules
checkTools
