name: push
description: combine multi-arch image and push
inputs:
  version:
    description: version
    required: true
  latest:
    description: if tag latest
    required: false
  workdir:
    description: workdir
    required: false    
runs:
  using: "composite"
  steps:
    - name: Build image
      env:
        VERSION: ${{ inputs.version }}
        LATEST: ${{ inputs.latest }}
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/master || "${GITHUB_REF}" == refs/tags/* ]]; then      
          minor_ver="${VERSION%.*}"
          major_ver="${minor_ver%.*}"
        
          tags=("${minor_ver}" "${major_ver}")
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            stability_tag=("${GITHUB_REF##*/}")
            tags=("${minor_ver}-${stability_tag}" "${major_ver}-${stability_tag}")
          else          
            if [[ -n "${LATEST}" ]]; then
              tags+=("latest")
            fi
          fi
        
          for tag in "${tags[@]}"; do
            TAG=${tag} make buildx-imagetools-create
          done
        fi
      shell: bash
      working-directory: ${{ inputs.workdir }}
